name: Build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: dotnet format --verify-no-changes
      - run: dotnet build -c Release
      - run: dotnet test -c Release